supermarket_dwh:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: analytics
      threads: 4
  target: dev
